### PR TITLE
Fix: serialize batch

### LINKED ISSUE #136: Non-chained batch() doesn't serialize
Found this while working on serialization in `memdown`.

@juliangruber @ralphtheninja

### PR DESCRIPTION
**Pull request by vweevers**
Closes #136. Before this, the `_serializeKey` and `_serializeValue`  functions were only called if you used the chained batch form, not if you used the array form.

### CODE REVIEW

**Comment by vweevers** [comment]
This breaks `memdown` in browsers, because [these](https://github.com/Level/abstract-leveldown/blob/24e11812d3e247bc2e6cb67955dd06614488333e/abstract/iterator-test.js#L10) abstract tests use numbers as values, `batch([..])` to write those values, and the behavior of `_serializeValue` is different if `process.browser` is true. 

That can be fixed quite easily, by not using numbers in those tests. I propose to establish a ground rule: abstract tests should exclusively use strings and buffers. Tests on any other types should be done in `encoding-down` or other stores if they support such types. 

WDYT @juliangruber @ralphtheninja?

Note as well that memdown currently has its own "serialization" in [its `_batch()` implementation](https://github.com/Level/memdown/blob/b51bbd30e1e16dd0d87b6acf40e863bb2eb37bc4/memdown.js#L197), with *again* a different behavior (no `process.browser` check here). Luckily, after we merge this PR and fix the abstract tests, we can remove the additional serialization from `memdown`, so that it all follows the same code path. We'll be far from done -- but at least the behavior of `put()` and `batch()` will be consistent. The next step would be to make browser and node consistent.

Perhaps another ground rule: `abstract-leveldown` is responsible for invoking serialization at the right time. The implementation should not (have to) do additional serialization in its `_put()` or `_batch()`.

**Comment by vweevers** [comment]
To clarify *ground rules*. I think we need a clear set of guidelines to:

1. Help us fix all the weirdness (`null/undefined`, `process.browser`, empty strings and buffers, identity encoding, serialization of range options).
2. Have something to fall back on for future additions and feature requests.

**Comment by juliangruber** [comment]
> That can be fixed quite easily, by not using numbers in those tests. I propose to establish a ground rule: abstract tests should exclusively use strings and buffers. Tests on any other types should be done in encoding-down or other stores if they support such types.

I agree 100%!

**Comment by juliangruber** [comment]
Wow, you're killing it again!

File: abstract-leveldown.js [hunk 1]
```diff
@@ -161,25 +161,31 @@ AbstractLevelDOWN.prototype.batch = function (array, options, callback) {
...
-  for (; i < l; i++) {
-    e = array[i]
-    if (typeof e != 'object')
+  var serialized = []
+
+  for (var i = 0; i < array.length; i++) {
+    if (typeof array[i] !== 'object')
       continue
 
+    var e = Object.assign({}, array[i])
```
Comment (vweevers) [inline abstract-leveldown.js]: Is `Object.assign` supported in all our target environments, or should I use a ponyfill?

Comment (juliangruber) [reply abstract-leveldown.js]: node 4 and up have it

Comment (vweevers) [reply abstract-leveldown.js]: Browsers too, except IE.

Comment (juliangruber) [reply abstract-leveldown.js]: edge has it, so imo we shouldn't worry

Comment (vweevers) [reply abstract-leveldown.js]: IE is currently included in memdown's sauce labs matrix; should we remove it?

Comment (vweevers) [reply abstract-leveldown.js]: It still has a [sizable market share](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers#Summary_tables) esp. compared to Edge. I think we shouldn't be too quick to drop it (like we did with node 4).

**Comment by vweevers** [comment]
We'll deal with IE later (in memdown to start, with docs and a polyfill in the test suite).

File: abstract-leveldown.js [hunk 2]
```diff
@@ -161,25 +161,31 @@ AbstractLevelDOWN.prototype.batch = function (array, options, callback) {
...
-    , e
-    , err
-
-  for (; i < l; i++) {
-    e = array[i]
-    if (typeof e != 'object')
+  var serialized = []
+
+  for (var i = 0; i < array.length; i++) {
+    if (typeof array[i] !== 'object')
```
Comment (vweevers) [inline abstract-leveldown.js]: Ooh, just realized this doesn't catch `null`

Comment (vweevers) [reply abstract-leveldown.js]: #138

File: abstract-leveldown.js (hunk 1 above)
Comment (vweevers) [reply abstract-leveldown.js]: Level/memdown#102
